@startuml
Alice11 -> Bob: Authentication Requests
Bob --> Alice11: Authentication Response

Alice11 -> Bob: Another authentication Request
Alice11 <-- Bob: Another authentication Response
@enduml
