name: Generate svg Diagrams
on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/architecture/**'
      - '.github/workflows/svg_diagrams.yml'
  workflow_dispatch:
    

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install graphviz
          sudo mkdir -p /opt/plantuml
          cd /opt/plantuml
          UML=https://github.com/plantuml/plantuml/releases/download/v1.2022.6/plantuml-1.2022.6.jar
          sudo curl -JLO ${UML}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: run command
        shell: bash
        run: |-
          package_name="QWERDTWSERa-2.7.0"
          git_tag=$(echo "$package_name" | tr '[:upper:]' '[:lower:]')
          echo "Package Name: $git_tag"
      - name: Process Diagrams
        run: java -jar /opt/plantuml/plantuml-1.2022.6.jar -v -tsvg -r -o "${{ github.workspace }}/docs/diagrams1" "docs/architecture/**.puml"
      - name: Commit Diagrams
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Adding Generated PlantUML Diagrams" || exit 0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Testing the create pull request
          branch: chores/svg_diagram_action
          labels: Diagram Action
          reviewers: VamshiAnumolu
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
